import {test,expect} from '@playwright/test';

test('HDL time scrollbar, cursor navigation and area zoom use the real VCD time range',async({page})=>{
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto('/hdl/viewer/index.html');
  const vcd='$timescale 1 ns $end\n$scope module tb $end\n$var wire 8 ! count $end\n$upscope $end\n$enddefinitions $end\n#0\nb00000000 !\n#10\nb00000101 !\n#20\nb00000010 !\n#70\nb00001001 !\n#100\n';
  await page.evaluate(vcd=>window.postMessage({type:'anacode-vcd',vcd},location.origin),vcd);
  const timeline=page.getByLabel('Digital waveform timeline'),cursor=page.getByLabel('Waveform cursor time',{exact:true}),scroll=page.getByRole('slider',{name:'Horizontal waveform position'});
  await expect(timeline).toHaveAttribute('data-viewer-ready','true');
  const time=async()=>Number(await cursor.getAttribute('data-time-seconds'));
  const view=async()=>({start:Number(await timeline.getAttribute('data-view-start-seconds')),end:Number(await timeline.getAttribute('data-view-end-seconds'))});
  await expect(scroll).toBeDisabled();
  await page.getByRole('button',{name:'Next signal transition',exact:true}).click();expect(await time()).toBeCloseTo(10e-9,14);
  await expect(page.getByLabel('Value of tb.count',{exact:true})).toHaveText('05');
  await page.getByRole('button',{name:'Next signal transition',exact:true}).click();expect(await time()).toBeCloseTo(20e-9,14);
  await page.getByRole('button',{name:'Previous signal transition',exact:true}).click();expect(await time()).toBeCloseTo(10e-9,14);
  const input=page.getByRole('textbox',{name:'Waveform cursor position'});await input.fill('50 ns');await input.press('Enter');
  await page.getByRole('button',{name:'Zoom in timeline',exact:true}).click();await expect(scroll).toBeEnabled();
  const before=await view(),width=before.end-before.start;
  const bounds=(await timeline.boundingBox())!,side=await timeline.evaluate(node=>parseFloat(getComputedStyle(node).getPropertyValue('--signal-width'))),plotWidth=bounds.width-side;
  await page.getByRole('button',{name:'Zoom to selected time area',exact:true}).click();await expect(timeline).toBeFocused();await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'Zoom to selected time area',exact:true})).toHaveAttribute('aria-pressed','false');
  await page.getByRole('button',{name:'Zoom to selected time area',exact:true}).click();
  await page.mouse.move(bounds.x+side+plotWidth*.2,bounds.y+55);await page.mouse.down();await page.mouse.move(bounds.x+side+plotWidth*.6,bounds.y+55,{steps:8});
  await expect(page.locator('.time-selection')).toBeVisible();await page.mouse.up();
  const after=await view();expect(after.start).toBeCloseTo(before.start+width*.2,9);expect(after.end).toBeCloseTo(before.start+width*.6,9);expect(await time()).toBeCloseTo(50e-9,14);
  await expect(page.locator('.time-selection')).toBeHidden();
  await scroll.focus();await scroll.press('End');const endView=await view();expect(endView.end).toBeCloseTo(100e-9,14);expect(await time()).toBeCloseTo(50e-9,14);
  await page.getByRole('button',{name:'Center view on cursor',exact:true}).click();const centered=await view();expect((centered.start+centered.end)/2).toBeCloseTo(50e-9,14);
  await timeline.hover({position:{x:side+100,y:60}});await page.mouse.wheel(150,0);await expect.poll(async()=>(await view()).start).toBeGreaterThan(centered.start);expect(await time()).toBeCloseTo(50e-9,14);
  await page.getByRole('button',{name:'Zoom to selected time area',exact:true}).click();const cancelView=await view();
  await page.mouse.move(bounds.x+side+plotWidth*.2,bounds.y+55);await page.mouse.down();await page.mouse.move(bounds.x+side+plotWidth*.4,bounds.y+55);await page.keyboard.press('Escape');await page.mouse.move(bounds.x+side+plotWidth*.6,bounds.y+55);await page.mouse.up();
  expect(await view()).toEqual(cancelView);expect(await time()).toBeCloseTo(50e-9,14);await expect(page.locator('.time-selection')).toBeHidden();
  await page.getByRole('button',{name:'Move cursor to end',exact:true}).click();expect(await time()).toBeCloseTo(100e-9,14);expect((await view()).end).toBeCloseTo(100e-9,14);
  await timeline.focus();await timeline.press('Home');expect(await time()).toBe(0);expect((await view()).start).toBe(0);
  await timeline.press('End');expect(await time()).toBeCloseTo(100e-9,14);
  await timeline.press('f');expect((await view()).end-(await view()).start).toBeCloseTo(100e-9,14);await expect(scroll).toBeDisabled();
  await timeline.press('z');await expect(page.getByRole('button',{name:'Zoom to selected time area'})).toHaveAttribute('aria-pressed','true');await timeline.press('Escape');await expect(page.getByRole('button',{name:'Zoom to selected time area'})).toHaveAttribute('aria-pressed','false');
  await page.getByRole('button',{name:/Shortcuts/}).click();await expect(page.getByRole('dialog')).toContainText('Shift + wheel / time scrollbar');await expect(page.getByRole('dialog')).toContainText('Zoom to a time area');await page.getByRole('dialog').press('Escape');
  await page.screenshot({path:'artifacts/qa/hdl-navigation-toolbar.png'});
  await page.getByRole('button',{name:'Zoom in timeline',exact:true}).click();
  await page.getByRole('button',{name:'Lock waveform view',exact:true}).click();
  const lockedView=await view(),lockedCursor=await time();await expect(scroll).toBeDisabled();
  for(const name of ['Zoom to selected time area','Move cursor to start','Move cursor to end','Fit timeline','Center view on cursor'])await expect(page.getByRole('button',{name,exact:true})).toBeDisabled();
  await timeline.focus();await timeline.press('Home');await timeline.press('f');await timeline.press('z');
  await timeline.hover({position:{x:side+100,y:60}});await page.keyboard.down('Shift');await page.mouse.wheel(0,-250);await page.keyboard.up('Shift');
  expect(await view()).toEqual(lockedView);expect(await time()).toBe(lockedCursor);
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
  await expect(page.getByRole('button',{name:/Shortcuts/})).toBeInViewport();
  expect(errors).toEqual([]);
});
