import { test, expect } from '@playwright/test';
import { HDL_CHALLENGES } from '../../lib/hdl-challenges';

test('HDL playground executes Icarus and renders actual VCD in the embedded viewer',async({page})=>{
  test.setTimeout(90_000);
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto('/hdl/playground');
  await expect(page.getByRole('textbox',{name:'Design source'})).toContainText('posedge clk');
  await page.getByRole('button',{name:'Run',exact:true}).click();
  await expect(page.getByRole('status')).toContainText('Finished',{timeout:30_000});
  const viewer=page.frameLocator('iframe[title="VCDrom logic waveform viewer"]');
  await expect(viewer.locator('canvas').first()).toBeVisible({timeout:25_000});
  expect(errors).toEqual([]);
  await page.screenshot({path:'artifacts/qa/hdl-workspace.png',fullPage:true});
  await expect(viewer.getByRole('alert')).toBeHidden();
  await page.getByRole('combobox',{name:'Output layout'}).selectOption('split');
  await expect(page.getByLabel('Simulator console')).toContainText('ANACODE_RESULT checks=64 failures=0');
  await expect(page.locator('iframe[title="VCDrom logic waveform viewer"]')).toBeVisible();
  await page.getByRole('combobox',{name:'Output layout'}).selectOption('stacked');
  await expect(page.getByLabel('Simulator console')).toBeVisible();
  await page.getByRole('button',{name:'Run',exact:true}).click();
  await expect(page.getByRole('status')).toContainText('Finished',{timeout:30_000});
  await expect(viewer.locator('canvas').first()).toBeVisible({timeout:25_000});
});

test('HDL checks distinguish wrong logic, fixed logic, syntax errors, and persist a draft',async({page})=>{
  test.setTimeout(90_000);
  const challenge=HDL_CHALLENGES[0];
  await page.goto(`/hdl/${challenge.slug}`);
  const editor=page.getByRole('textbox',{name:'Design source'});
  await editor.fill(challenge.solution.replace('sel==0 ? a : sel==1 ? b : sel==2 ? c : d','a'));
  await page.getByRole('tab',{name:'tb.sv',exact:true}).click();
  await page.getByRole('textbox',{name:'Testbench source',exact:true}).fill('module tb; initial begin $display("ANACODE_RESULT checks=64 failures=0"); $finish; end endmodule');
  await page.getByRole('tab',{name:'Supplied tests',exact:true}).click();
  await expect(page.getByRole('textbox',{name:'Supplied testbench source'})).toHaveAttribute('aria-readonly','true');
  await page.getByRole('tab',{name:'design.sv',exact:true}).click();
  await page.getByRole('button',{name:'Submit',exact:true}).click();
  await expect(page.getByRole('status')).toContainText('Some practice checks failed',{timeout:30_000});
  await expect(page.getByLabel('Submission diagnostics')).toContainText('FAIL: Selected word');
  await expect(page.getByLabel('Test case results')).toContainText('18 / 64 checks passed');
  await editor.fill(challenge.solution);
  await page.getByRole('button',{name:'Submit',exact:true}).click();
  await expect(page.getByRole('status')).toContainText('All 64 practice checks passed',{timeout:30_000});
  await page.getByRole('tab',{name:'Waveforms',exact:true}).click();
  await expect(page.frameLocator('iframe[title="VCDrom logic waveform viewer"]').locator('canvas').first()).toBeVisible({timeout:25_000});
  await editor.fill(`${challenge.solution}\n// revision`);
  await expect(page.getByRole('status')).toContainText('Draft changed');
  await expect(page.getByRole('button',{name:'VCD',exact:true})).toBeDisabled();
  await page.reload();
  await expect(editor).toContainText('sel==0 ? a');
  await editor.fill('module top_module(input a output y); endmodule');
  await page.getByRole('button',{name:'Run',exact:true}).click();
  await expect(page.getByRole('status')).toContainText('Compile or simulation error',{timeout:30_000});
  await expect(page.getByLabel('Simulator console')).toContainText('design.v');
  await page.getByRole('tab',{name:'Test results',exact:true}).click();
  await page.getByRole('button',{name:/^design.sv:1/}).first().click();
  await expect(editor).toBeFocused();
});

test('HDL is discoverable from analog practice and has searchable local progress on mobile',async({page})=>{
  await page.setViewportSize({width:390,height:844});
  await page.goto('/problems');
  await page.getByRole('navigation',{name:'Practice tracks'}).getByRole('link',{name:/Verilog/}).click();
  await expect(page.getByRole('heading',{name:'Verilog & SystemVerilog practice'})).toBeVisible();
  await page.getByRole('textbox',{name:'Search HDL problems'}).fill('SAR');
  await expect(page.getByRole('region',{name:'HDL exercises'}).getByRole('link')).toHaveCount(1);
  await page.getByRole('link',{name:/Sequence a SAR conversion/}).click();
  await expect(page.getByRole('button',{name:'Submit',exact:true})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBeTruthy();
  await page.getByRole('link',{name:'Problem list',exact:true}).click();
  await page.getByRole('textbox',{name:'Search HDL problems'}).fill('');
  await page.evaluate(()=>{localStorage.setItem('anacode-hdl-progress-v1',JSON.stringify({'word-multiplexer':{passed:true,checks:64,failures:0,submittedAt:new Date().toISOString()}}));window.dispatchEvent(new Event('anacode-hdl-progress'));});
  await page.getByRole('combobox',{name:'HDL status'}).selectOption('Passed');
  await expect(page.getByRole('region',{name:'HDL exercises'}).getByRole('link')).toHaveCount(1);
  await expect(page.getByRole('link',{name:/Route a data word/})).toContainText('64 checks');
});

test('HDL search waits for its handlers before accepting input when client scripts are delayed',async({page})=>{
  await page.setViewportSize({width:390,height:844});
  let releaseScripts:()=>void=()=>{};
  const scriptsReady=new Promise<void>(resolve=>{releaseScripts=resolve;});
  await page.route('**/*',async route=>{
    if(route.request().resourceType()==='script')await scriptsReady;
    await route.continue();
  });
  try {
    await page.goto('/hdl',{waitUntil:'commit'});
    const library=page.getByRole('region',{name:'HDL exercises'});
    const search=page.getByRole('textbox',{name:'Search HDL problems'});
    await expect(search).toBeVisible();
    await expect(search).toBeDisabled();
    await expect(library).toHaveAttribute('aria-busy','true');
    for(const name of ['HDL difficulty','HDL topic','HDL status'])await expect(page.getByRole('combobox',{name})).toBeDisabled();
    await expect(library.getByRole('link')).toHaveCount(6);
    await expect(library.getByRole('link').first()).toHaveAttribute('href','/hdl/word-multiplexer');
    releaseScripts();
    await expect(search).toBeEnabled();
    await search.fill('SAR');
    await expect(library.getByRole('link')).toHaveCount(1);
    await expect(library.getByRole('link')).toContainText('Sequence a SAR conversion');
    await page.getByRole('combobox',{name:'HDL difficulty'}).selectOption('Easy');
    await expect(library.getByRole('link')).toHaveCount(0);
    await page.getByRole('combobox',{name:'HDL difficulty'}).selectOption('Hard');
    await expect(library.getByRole('link')).toHaveCount(1);
    await expect(search).toHaveValue('SAR');
    await expect(library).toHaveAttribute('aria-busy','false');
  } finally { releaseScripts(); }
});

test('HDL panes resize with keyboard and pointer while editor state survives file switches',async({page})=>{
  await page.goto('/hdl/word-multiplexer');
  const editor=page.getByRole('textbox',{name:'Design source'}), code=page.getByRole('region',{name:'HDL source files'});
  await expect(editor).toBeVisible();
  const side=page.getByRole('separator',{name:'Resize problem description'});
  const before=(await code.boundingBox())!.width;
  await side.focus();await side.press('ArrowRight');await side.press('ArrowRight');
  expect((await code.boundingBox())!.width).toBeLessThan(before-20);
  const vertical=page.getByRole('separator',{name:'Resize editor and results'}), initialHeight=(await code.boundingBox())!.height;
  const handle=(await vertical.boundingBox())!;
  await page.mouse.move(handle.x+handle.width/2,handle.y+handle.height/2);await page.mouse.down();await page.mouse.move(handle.x+handle.width/2,handle.y+handle.height/2+55,{steps:6});await page.mouse.up();
  expect((await code.boundingBox())!.height).toBeGreaterThan(initialHeight+30);
  await editor.fill(HDL_CHALLENGES[0].solution);
  await page.getByRole('combobox',{name:'HDL language'}).selectOption('2005');
  await page.getByRole('button',{name:'Submit',exact:true}).click();
  await expect(page.getByRole('status')).toContainText('All 64 practice checks passed',{timeout:30_000});
  await page.setViewportSize({width:1280,height:720});
  await vertical.focus();await vertical.press('End');
  await expect(vertical).toHaveAttribute('aria-controls',(await code.getAttribute('id'))!);
  const results=(await page.getByRole('region',{name:'HDL simulation results'}).boundingBox())!;
  const codingBottom=await code.evaluate(element=>element.parentElement!.getBoundingClientRect().bottom);
  expect(results.y+results.height).toBeLessThanOrEqual(codingBottom+1);
  await editor.press('ControlOrMeta+End');await editor.pressSequentially('// kept undo history');
  await page.getByRole('tab',{name:'tb.sv',exact:true}).click();await page.getByRole('tab',{name:'design.sv',exact:true}).click();
  await editor.press('ControlOrMeta+z');
  await expect(editor).not.toContainText('// kept undo history');
  await expect(editor).toContainText('assign y = sel==0');
});

test('HDL runaway execution can be stopped without freezing the editor',async({page})=>{
  await page.goto('/hdl/playground');
  await expect(page.getByRole('textbox',{name:'Design source'})).toBeVisible();
  await page.getByRole('tab',{name:'tb.sv'}).click();
  await page.getByRole('textbox',{name:'Testbench source'}).fill('module tb; integer i=0; initial forever i=i+1; endmodule');
  await page.getByRole('button',{name:'Run',exact:true}).click();
  await expect(page.getByRole('status')).toContainText('Simulating',{timeout:20_000});
  await page.getByRole('button',{name:'Stop',exact:true}).click();
  await expect(page.getByLabel('Simulator console')).toContainText('Simulation stopped');
  await expect(page.getByRole('button',{name:'Run',exact:true})).toBeEnabled();
});

test('HDL fills the window with three code/results layouts and bounded waveform help',async({page})=>{
  test.setTimeout(90_000);
  await page.setViewportSize({width:1440,height:900});
  await page.goto('/hdl/playground');
  const editor=page.getByRole('textbox',{name:'Design source'});
  await expect(editor).toBeVisible();
  const original=await editor.innerText();
  await editor.press('ControlOrMeta+Enter');
  await expect(page.getByRole('status')).toContainText('Finished',{timeout:30_000});
  expect(await editor.innerText()).toBe(original);
  const code=page.getByRole('region',{name:'HDL source files'}), results=page.getByRole('region',{name:'HDL simulation results'});
  const viewer=page.frameLocator('iframe[title="VCDrom logic waveform viewer"]');
  await expect(viewer.locator('canvas').first()).toBeVisible({timeout:25_000});
  const workbench=(await page.getByRole('region',{name:'HDL workbench'}).boundingBox())!;
  expect(workbench.x).toBeLessThan(10);expect(workbench.width).toBeGreaterThan(1420);expect(workbench.y+workbench.height).toBeGreaterThan(890);
  await expect(page.getByRole('contentinfo')).toHaveCount(0);
  expect((await results.boundingBox())!.y).toBeGreaterThan((await code.boundingBox())!.y);
  await page.screenshot({path:'artifacts/qa/hdl-window-stacked.png'});
  await page.getByRole('button',{name:'Switch to dark mode'}).click();
  await expect(page.locator('html')).toHaveAttribute('data-theme','dark');
  await viewer.getByRole('button',{name:/Shortcuts/}).click();
  const dialog=viewer.getByRole('dialog',{name:'Waveform shortcuts'});
  await expect(dialog).toBeVisible();
  // Its shortcut table comes from the loaded VCDrom build, not a guessed list.
  expect(await dialog.locator('.wd-help-panel-row').count()).toBeGreaterThan(8);
  expect(await dialog.evaluate(element=>{
    const box=element.getBoundingClientRect();
    return box.top>=0&&box.left>=0&&box.bottom<=innerHeight&&box.right<=innerWidth&&getComputedStyle(element).backgroundColor==='rgb(19, 32, 42)';
  })).toBeTruthy();
  await page.screenshot({path:'artifacts/qa/hdl-window-help.png'});
  await viewer.getByRole('button',{name:'Close waveform shortcuts'}).click();
  await expect(dialog).toBeHidden();
  await viewer.getByRole('button',{name:/Shortcuts/}).press('?');
  await expect(dialog).toBeVisible();await dialog.press('Escape');await expect(dialog).toBeHidden();
  await page.getByRole('combobox',{name:'Workspace layout'}).selectOption('split');
  const codeBox=(await code.boundingBox())!,resultBox=(await results.boundingBox())!;
  expect(resultBox.x).toBeGreaterThan(codeBox.x+codeBox.width);expect(Math.abs(resultBox.y-codeBox.y)).toBeLessThan(2);
  await page.screenshot({path:'artifacts/qa/hdl-window-side-by-side.png'});
  const divider=page.getByRole('separator',{name:'Resize editor and results'});
  await expect(divider).toHaveAttribute('aria-orientation','vertical');
  await divider.focus();await divider.press('ArrowRight');
  expect((await code.boundingBox())!.width).toBeGreaterThan(codeBox.width);
  await page.getByRole('combobox',{name:'Workspace layout'}).selectOption('tabs');
  await expect(code).toBeHidden();await expect(results).toBeVisible();
  await page.getByRole('tab',{name:'Code',exact:true}).click();
  expect(await editor.innerText()).toBe(original);await expect(results).toBeHidden();
  await page.getByRole('tab',{name:'Results',exact:true}).click();
  await expect(viewer.locator('canvas').first()).toBeVisible();
  await page.screenshot({path:'artifacts/qa/hdl-window-tabs.png'});
  await page.setViewportSize({width:390,height:844});
  await expect(page.getByRole('button',{name:'Description',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Description',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Your digital design playground'})).toBeVisible();
  await page.getByRole('button',{name:'Back to code',exact:true}).click();
  await expect(results).toBeVisible();
  await viewer.getByRole('button',{name:/Shortcuts/}).click();
  expect(await dialog.evaluate(element=>{const box=element.getBoundingClientRect();return box.bottom<=innerHeight&&box.right<=innerWidth;})).toBeTruthy();
  await page.screenshot({path:'artifacts/qa/hdl-window-mobile-help.png'});
  await viewer.getByRole('button',{name:'Close waveform shortcuts'}).click();
  await page.getByRole('combobox',{name:'Workspace layout'}).selectOption('stacked');
  await expect(code).toBeVisible();await expect(results).toBeVisible();
  await page.screenshot({path:'artifacts/qa/hdl-window-mobile-stacked.png'});
  await page.getByRole('combobox',{name:'Workspace layout'}).selectOption('split');
  await expect(code).toBeVisible();await expect(results).toBeVisible();
  expect((await results.boundingBox())!.y).toBeGreaterThan((await code.boundingBox())!.y);
  expect((await page.locator('iframe[title="VCDrom logic waveform viewer"]').boundingBox())!.width).toBeGreaterThan(360);
  await expect(page.getByText('Side by side uses stacked panes on small screens.')).toBeVisible();
  await page.screenshot({path:'artifacts/qa/hdl-window-mobile-responsive-split.png'});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&document.documentElement.scrollHeight<=innerHeight)).toBeTruthy();
});

test('HDL submit shortcuts work inside CodeMirror and run shortcuts cross the viewer boundary',async({page})=>{
  test.setTimeout(90_000);
  await page.goto('/hdl/word-multiplexer');
  const editor=page.getByRole('textbox',{name:'Design source'});
  await editor.fill(HDL_CHALLENGES[0].solution);
  const original=await editor.innerText();
  await editor.press('ControlOrMeta+Shift+Enter');
  await expect(page.getByRole('status')).toContainText('All 64 practice checks passed',{timeout:30_000});
  expect(await editor.innerText()).toBe(original);
  await page.getByRole('tab',{name:'Waveforms',exact:true}).click();
  const viewer=page.frameLocator('iframe[title="VCDrom logic waveform viewer"]');
  await expect(viewer.locator('canvas').first()).toBeVisible({timeout:25_000});
  await viewer.getByRole('button',{name:/Shortcuts/}).press('ControlOrMeta+Enter');
  await expect(page.getByRole('status')).toContainText('Finished',{timeout:30_000});
  await expect(viewer.locator('canvas').first()).toBeVisible({timeout:25_000});
  expect(await editor.innerText()).toBe(original);
});
